# General application settings
app_name: "MVC_Assignment"
port: 3000
debug_mode: true

# Database connection settings
db:
  host: "db"
  port: 3306
  user: "kitchen"
  password: "god"
  db_name: "kitchen"


# A list o enabled features
feature_flags:
  - "new_dashboard"
  - "beta_user_testing"
  - "api_rate_limiting"
