version: '3.8'
services:
  app:
    build: .
    container_name: go_server
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: kitchen
      MYSQL_PASSWORD: god
      MYSQL_DBNAME: kitchen
      MYSQL_PORT: 3306
      MAX_OPEN_CONNECTIONS: 500
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: kitchen
      MYSQL_USER: kitchen
      MYSQL_PASSWORD: god
      MYSQL_ROOT_PASSWORD: god
    ports:
      - "3307:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
