
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL ,
  mail VARCHAR(1024),
  phone VARCHAR(20),
  isAdmin BOOL NOT NULL,
  isCheff BOOL NOT NULL,
  score FLOAT DEFAULT 0 NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL 
);

