
CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  table_no INT NOT NULL,
  complete BOOL NOT NULL DEFAULT FALSE,
  FOREIGN KEY(user_id) REFERENCES users(id)
);

